import type { Metadata } from 'next'
import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'
import localFont from 'next/font/local'
import './globals.css'
import Providers from '@/providers/providers'
import { Navbar } from '@/components/navbar'
import { Footer } from '@/components/footer'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // We suppress the Hydration warning because of the next-themes package.
    // It requires this to be set since, we don't really know the user theme preference on the server side.
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-auto flex min-h-screen max-w-3xl flex-col px-2 antialiased`}
      >
        <Providers>
          <Navbar />
          <main className='mt-40 max-w-3xl grow'>{children}</main>
          <Footer />

          {/* Vercel Analytics and Speed Insights */}
          {/* NOTE: Don't edit/remove these components */}
          <Analytics />
          <SpeedInsights />
        </Providers>
      </body>
    </html>
  )
}
